<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.4.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\default-background.jpg" LogicalName="default-background.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="SocketIOClient" Version="4.0.5" />
    <PackageReference Include="Velopack" Version="1.2.158" />
  </ItemGroup>

</Project>